// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXzbGP2FE9yx7JgIJwOxW9MdwUaUa5NnU',
    appId: '1:841287443686:web:a351e4c1f7005b2d9fc727',
    messagingSenderId: '841287443686',
    projectId: 'quisi-8787',
    authDomain: 'quisi-8787.firebaseapp.com',
    storageBucket: 'quisi-8787.firebasestorage.app',
    measurementId: 'G-1YHQ26WSL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwtr6wWnGqMzlo6Xc8mYMHhq3JjQYWY6c',
    appId: '1:841287443686:android:3b524e647e57a00b9fc727',
    messagingSenderId: '841287443686',
    projectId: 'quisi-8787',
    storageBucket: 'quisi-8787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0C3sgpQHnHVJbApd83PW3vw5FXm0aM28',
    appId: '1:841287443686:ios:e704a096f90032439fc727',
    messagingSenderId: '841287443686',
    projectId: 'quisi-8787',
    storageBucket: 'quisi-8787.firebasestorage.app',
    iosClientId: '841287443686-rpacc9dbflr3iqti1v9c92odgc2a3jgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.quisi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0C3sgpQHnHVJbApd83PW3vw5FXm0aM28',
    appId: '1:841287443686:ios:e704a096f90032439fc727',
    messagingSenderId: '841287443686',
    projectId: 'quisi-8787',
    storageBucket: 'quisi-8787.firebasestorage.app',
    iosClientId: '841287443686-rpacc9dbflr3iqti1v9c92odgc2a3jgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.quisi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXzbGP2FE9yx7JgIJwOxW9MdwUaUa5NnU',
    appId: '1:841287443686:web:83513fcd0a356c089fc727',
    messagingSenderId: '841287443686',
    projectId: 'quisi-8787',
    authDomain: 'quisi-8787.firebaseapp.com',
    storageBucket: 'quisi-8787.firebasestorage.app',
    measurementId: 'G-48ETW31N7J',
  );
}
